// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCookBook.EntityFramework;

#nullable disable

namespace MyCookBook.EntityFramework.Migrations
{
    [DbContext(typeof(MyCookBookDbContext))]
    [Migration("20250709191558_get-rid-of-image-id-8")]
    partial class getridofimageid8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("MyCookBook.Domain.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Directions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Minutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawThumbnailData")
                        .HasColumnType("BLOB");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MyCookBook.Domain.Models.RecipeBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecipeBooks");
                });

            modelBuilder.Entity("MyCookBook.Domain.Models.RecipeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MyCookBook.Domain.Models.RecipeImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawImageData")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("MyCookBook.Domain.Models.Recipe", b =>
                {
                    b.HasOne("MyCookBook.Domain.Models.RecipeCategory", null)
                        .WithMany("Recipes")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCookBook.Domain.Models.RecipeCategory", b =>
                {
                    b.HasOne("MyCookBook.Domain.Models.RecipeBook", null)
                        .WithMany("Categories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCookBook.Domain.Models.RecipeImage", b =>
                {
                    b.HasOne("MyCookBook.Domain.Models.Recipe", null)
                        .WithOne("Image")
                        .HasForeignKey("MyCookBook.Domain.Models.RecipeImage", "ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCookBook.Domain.Models.Recipe", b =>
                {
                    b.Navigation("Image");
                });

            modelBuilder.Entity("MyCookBook.Domain.Models.RecipeBook", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("MyCookBook.Domain.Models.RecipeCategory", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
