// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCookBook.EntityFramework;

#nullable disable

namespace MyCookBook.EntityFramework.Migrations
{
    [DbContext(typeof(MyCookBookDbContext))]
    partial class MyCookBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("MyCookBook.EntityFramework.DTOs.RecipeCategoryDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MyCookBook.EntityFramework.DTOs.RecipeDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Directions")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Ingredients")
                        .HasColumnType("TEXT");

                    b.Property<int>("Minutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipeCategoryDTOId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeCategoryDTOId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MyCookBook.EntityFramework.DTOs.RecipeDTO", b =>
                {
                    b.HasOne("MyCookBook.EntityFramework.DTOs.RecipeCategoryDTO", null)
                        .WithMany("Recipes")
                        .HasForeignKey("RecipeCategoryDTOId");
                });

            modelBuilder.Entity("MyCookBook.EntityFramework.DTOs.RecipeCategoryDTO", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
